spring:
  application:
    name: intersection-app


intersection-app:
  leaving:
    tick: 2s
  semaphores:
    - type: NORTH_SOUTH
      tick: 10s
    - type: WEST_EAST
      tick: 15s
  cars:
    - type: NORTH_TO_SOUTH
      tick: 1m
      amount: 6
    - type: SOUTH_TO_NORTH
      tick: 1m
      amount: 3
    - type: WEST_TO_EAST
      tick: 1m
      amount: 7
    - type: EAST_TO_WEST
      tick: 1m
      amount: 8
